name: Create Build Folder

on:
  push:
    branches:
      - main

jobs:
  create-build-folder:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create Build Directory
        run: |
          mkdir test
          mkdir test/css

      # Add more steps as needed for your workflow
